package main

import (
	"flag"
	"fmt"
	"net/http"
	"os"

	"jam/bazaar"
)

// generated by import-pages
import (
	_"jam/pages/register"
)

func main() {
	flag.Parse()
	if !flag.Parsed() { os.Exit(1) }

	bazaar.Connect()


	fmt.Println("jam: comin' up... comin' up... comin' up...")
	http.ListenAndServe(":8080", nil)
}
